import { useState } from "react";
import { ArrowDownLeft,ArrowUpRight,Landmark,PiggyBank,TrendingUp,WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { RichTextEditor } from "@/components/common/RichTextEditor";
import { useLGList,useLGMutations } from "@/hooks/use-life-graph";
import { useAuth } from "@/hooks/use-auth";
import { formatMoney } from "@/lib/money";
const tabs=[["budgets","Presupuestos"],["debts","Deudas"],["savings","Ahorro"],["investments","Inversiones"],["external","Fuentes externas"]] as const;
export function FinanceAdvancedPanel(){
 const [tab,setTab]=useState<(typeof tabs)[number][0]>("budgets");
 return <section className="space-y-3 rounded-2xl border border-border p-3" data-testid="finance-advanced"><div className="flex flex-wrap gap-1.5">{tabs.map(([k,v])=><button key={k} type="button" onClick={()=>setTab(k)} className={"rounded-full border px-3 py-1.5 text-xs "+(tab===k?"border-primary bg-primary/10":"border-border text-muted-foreground")}>{v}</button>)}</div>{tab==="budgets"?<Budgets/>:tab==="debts"?<Debts/>:tab==="savings"?<Savings/>:tab==="investments"?<Investments/>:<ExternalSources/>}</section>;
}
function Budgets(){const q=useLGList("finance_budgets");const m=useLGMutations("finance_budgets");const{user}=useAuth();const[name,setName]=useState(""),[amount,setAmount]=useState(""),[start,setStart]=useState(""),[notes,setNotes]=useState("");return <Panel title="Presupuestos" icon={<WalletCards className="h-4 w-4"/>}><div className="grid gap-2 sm:grid-cols-4"><Input placeholder="Presupuesto" value={name} onChange={e=>setName(e.target.value)}/><Input type="number" placeholder="Monto" value={amount} onChange={e=>setAmount(e.target.value)}/><Input type="date" value={start} onChange={e=>setStart(e.target.value)}/><Button disabled={!name.trim()} onClick={()=>void m.create.mutateAsync({user_id:user?.id,name:name.trim(),amount:Number(amount)||0,period:"monthly",start_on:start||new Date().toISOString().slice(0,10),notes:notes||null}).then(()=>setName(""))}>Crear</Button></div><RichTextEditor value={notes} onChange={setNotes} placeholder="Reglas o notas…"/>{(q.data||[]).map((x:any)=><div key={x.id} className="rounded-xl border p-3 text-sm"><b>{x.name}</b><span className="ml-2">{formatMoney(Number(x.amount)||0)}</span><span className="ml-2 text-xs text-muted-foreground">{x.period}</span></div>)}</Panel>}
function Debts(){const q=useLGList("finance_debts");const m=useLGMutations("finance_debts");const{user}=useAuth();const[name,setName]=useState(""),[principal,setPrincipal]=useState(""),[balance,setBalance]=useState(""),[due,setDue]=useState(""),[notes,setNotes]=useState("");return <Panel title="Deudas" icon={<ArrowDownLeft className="h-4 w-4"/>}><div className="grid gap-2 sm:grid-cols-4"><Input placeholder="Deuda / préstamo" value={name} onChange={e=>setName(e.target.value)}/><Input type="number" placeholder="Principal" value={principal} onChange={e=>setPrincipal(e.target.value)}/><Input type="number" placeholder="Saldo" value={balance} onChange={e=>setBalance(e.target.value)}/><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></div><RichTextEditor value={notes} onChange={setNotes} placeholder="Interés, pagos, condiciones…"/><Button disabled={!name.trim()} onClick={()=>void m.create.mutateAsync({user_id:user?.id,name:name.trim(),principal:Number(principal)||0,balance:Number(balance)||0,due_on:due||null,notes:notes||null}).then(()=>setName(""))}>Registrar deuda</Button>{(q.data||[]).map((x:any)=><div key={x.id} className="rounded-xl border p-3 text-sm"><b>{x.name}</b> · saldo {formatMoney(Number(x.balance)||0)}{x.due_on?" · "+x.due_on:""}</div>)}</Panel>}
function Savings(){const q=useLGList("finance_savings_goals");const m=useLGMutations("finance_savings_goals");const{user}=useAuth();const[name,setName]=useState(""),[target,setTarget]=useState(""),[current,setCurrent]=useState(""),[date,setDate]=useState(""),[notes,setNotes]=useState("");return <Panel title="Metas de ahorro" icon={<PiggyBank className="h-4 w-4"/>}><div className="grid gap-2 sm:grid-cols-4"><Input placeholder="Meta" value={name} onChange={e=>setName(e.target.value)}/><Input type="number" placeholder="Objetivo" value={target} onChange={e=>setTarget(e.target.value)}/><Input type="number" placeholder="Actual" value={current} onChange={e=>setCurrent(e.target.value)}/><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><RichTextEditor value={notes} onChange={setNotes} placeholder="Para qué es, estrategia…"/><Button disabled={!name.trim()} onClick={()=>void m.create.mutateAsync({user_id:user?.id,name:name.trim(),target_amount:Number(target)||0,current_amount:Number(current)||0,target_date:date||null,notes:notes||null}).then(()=>setName(""))}>Crear meta</Button>{(q.data||[]).map((x:any)=>{const p=Number(x.target_amount)?Math.min(100,Number(x.current_amount)/Number(x.target_amount)*100):0;return <div key={x.id} className="rounded-xl border p-3 text-sm"><div className="flex justify-between"><b>{x.name}</b><span>{Math.round(p)}%</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{width:p+"%"}}/></div></div>})}</Panel>}
function Investments(){const q=useLGList("finance_investments");const m=useLGMutations("finance_investments");const{user}=useAuth();const[name,setName]=useState(""),[invested,setInvested]=useState(""),[value,setValue]=useState(""),[type,setType]=useState(""),[notes,setNotes]=useState("");return <Panel title="Inversiones" icon={<TrendingUp className="h-4 w-4"/>}><div className="grid gap-2 sm:grid-cols-4"><Input placeholder="Activo / inversión" value={name} onChange={e=>setName(e.target.value)}/><Input placeholder="Tipo" value={type} onChange={e=>setType(e.target.value)}/><Input type="number" placeholder="Invertido" value={invested} onChange={e=>setInvested(e.target.value)}/><Input type="number" placeholder="Valor actual" value={value} onChange={e=>setValue(e.target.value)}/></div><RichTextEditor value={notes} onChange={setNotes} placeholder="Tesis, riesgo, notas…"/><Button disabled={!name.trim()} onClick={()=>void m.create.mutateAsync({user_id:user?.id,name:name.trim(),asset_type:type||null,invested_amount:Number(invested)||0,current_value:Number(value)||0,notes:notes||null}).then(()=>setName(""))}>Registrar</Button>{(q.data||[]).map((x:any)=><div key={x.id} className="rounded-xl border p-3 text-sm"><b>{x.name}</b> · {formatMoney(Number(x.current_value)||0)}<span className="ml-2 text-xs text-muted-foreground">{x.asset_type||"activo"}</span></div>)}</Panel>}
function ExternalSources(){const q=useLGList("finance_external_snapshots","period_end");const totalI=(q.data||[]).reduce((a:any,x:any)=>a+Number(x.income||0),0);const totalE=(q.data||[]).reduce((a:any,x:any)=>a+Number(x.expense||0),0);return <Panel title="Fuentes externas" icon={<Landmark className="h-4 w-4"/>}><div className="rounded-xl border p-3"><p className="text-xs text-muted-foreground">WíswellArt · consolidado de snapshots recibidos</p><div className="mt-2 grid grid-cols-3 gap-2 text-sm"><span>Ingresos <b>{formatMoney(totalI)}</b></span><span>Egresos <b>{formatMoney(totalE)}</b></span><span>Resultado <b>{formatMoney(totalI-totalE)}</b></span></div></div>{(q.data||[]).map((x:any)=><div key={x.id} className="flex items-center justify-between rounded-xl border p-3 text-xs"><span>{x.period_start} → {x.period_end}</span><span><ArrowUpRight className="mr-1 inline h-3.5 w-3.5"/>{formatMoney(Number(x.income)||0)} · <ArrowDownLeft className="mr-1 inline h-3.5 w-3.5"/>{formatMoney(Number(x.expense)||0)}</span></div>)}</Panel>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="space-y-3"><div className="flex items-center gap-2"><span>{icon}</span><h2 className="font-semibold">{title}</h2></div>{children}</div>}
