import { useState } from "react";
import { Calculator, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useGlobalDate } from "@/hooks/use-global-date";
import { useHealthMetricMutation, usePersonalDateList } from "@/hooks/use-personal-domains";
import { HelpTip } from "@/components/common/HelpTip";

type Metric={id:string;metric_date:string;weight_kg:number|null;height_cm:number|null;waist_cm:number|null;body_fat_pct:number|null;systolic:number|null;diastolic:number|null;resting_hr:number|null;sleep_hours:number|null;exercise_minutes:number|null;water_liters:number|null;notes:string|null};
export function HealthMetricsPanel(){
 const {date}=useGlobalDate();const q=usePersonalDateList<Metric>("health_metrics","metric_date",date);const save=useHealthMetricMutation();const current=q.data?.[0];
 const [weight,setWeight]=useState(current?.weight_kg?.toString()??"");const [height,setHeight]=useState(current?.height_cm?.toString()??"");const [waist,setWaist]=useState(current?.waist_cm?.toString()??"");const [sleep,setSleep]=useState(current?.sleep_hours?.toString()??"");const [exercise,setExercise]=useState(current?.exercise_minutes?.toString()??"");const [water,setWater]=useState(current?.water_liters?.toString()??"");const [notes,setNotes]=useState(current?.notes??"");
 const bmi=Number(weight)>0&&Number(height)>0?Number(weight)/Math.pow(Number(height)/100,2):null;
 const submit=async()=>{await save.mutateAsync({user_id:(await import("@/integrations/supabase/client")).supabase.auth.getUser?undefined:undefined});};
 const persist=async()=>{const {data}=await (await import("@/integrations/supabase/client")).supabase.auth.getUser();if(!data.user)return;await save.mutateAsync({user_id:data.user.id,metric_date:date,weight_kg:weight?Number(weight):null,height_cm:height?Number(height):null,waist_cm:waist?Number(waist):null,sleep_hours:sleep?Number(sleep):null,exercise_minutes:exercise?Number(exercise):null,water_liters:water?Number(water):null,notes:notes||null});};
 return <section className="glass space-y-4 rounded-2xl p-4"><div><div className="flex items-center gap-2"><h2 className="font-semibold">Métricas de salud</h2><HelpTip helpKey="health.metrics"/></div><p className="text-xs text-muted-foreground">Registro por fecha global. El IMC se calcula, no se escribe manualmente.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><label className="text-xs text-muted-foreground">Peso (kg)<Input className="mt-1" inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label className="text-xs text-muted-foreground">Estatura (cm)<Input className="mt-1" inputMode="decimal" value={height} onChange={e=>setHeight(e.target.value)}/></label><div className="rounded-xl border p-2"><p className="text-xs text-muted-foreground">IMC <HelpTip helpKey="health.bmi"/></p><p className="mt-1 text-xl font-semibold">{bmi?bmi.toFixed(1):"—"}</p></div><label className="text-xs text-muted-foreground">Cintura (cm)<Input className="mt-1" inputMode="decimal" value={waist} onChange={e=>setWaist(e.target.value)}/></label><label className="text-xs text-muted-foreground">Sueño (h)<Input className="mt-1" inputMode="decimal" value={sleep} onChange={e=>setSleep(e.target.value)}/></label><label className="text-xs text-muted-foreground">Ejercicio (min)<Input className="mt-1" inputMode="numeric" value={exercise} onChange={e=>setExercise(e.target.value)}/></label><label className="text-xs text-muted-foreground">Agua (L)<Input className="mt-1" inputMode="decimal" value={water} onChange={e=>setWater(e.target.value)}/></label></div><label className="text-xs text-muted-foreground">Notas<textarea className="mt-1 min-h-20 w-full rounded-md border bg-background p-2 text-sm" value={notes} onChange={e=>setNotes(e.target.value)}/></label><Button onClick={()=>void persist()} disabled={save.isPending}><Save className="mr-2 h-4 w-4"/>Guardar métricas</Button>{q.isLoading&&<p className="text-xs text-muted-foreground">Cargando registro…</p>}</section>;
}