import { useEffect,useMemo,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Bell,BellOff,Check,Clock,Plus,Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { RichTextEditor } from "@/components/common/RichTextEditor";
import { GlobalDateHeader } from "@/components/common/GlobalDateHeader";
import { EmptyState } from "@/components/common/EmptyState";
import { HelpTip } from "@/components/common/HelpTip";
import { usePersonalList,usePersonalMutations } from "@/hooks/use-personal-domains";
import { personalDomainsService } from "@/services/personal-domains.service";
import { useAuth } from "@/hooks/use-auth";
import { cn } from "@/lib/utils";
import { lifeGraphService } from "@/services/life-graph.service";
type Alarm={id:string;user_id:string;title:string;description:string|null;alarm_at:string;repeat_rule:string;enabled:boolean;snoozed_until:string|null;last_fired_at:string|null};
export const Route=createFileRoute("/_authenticated/alarmas")({component:AlarmPage});
function AlarmPage(){
 const {user}=useAuth();const q=usePersonalList<Alarm>("alarms","alarm_at");const m=usePersonalMutations("alarms");
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[when,setWhen]=useState(""),[repeat,setRepeat]=useState("once"),[permission,setPermission]=useState<NotificationPermission>("default");
 useEffect(()=>{if(typeof window!=="undefined"&&"Notification"in window)setPermission(Notification.permission)},[]);
 useEffect(()=>{if(!q.data||typeof window==="undefined")return;const tick=()=>{const now=Date.now();for(const a of q.data){if(!a.enabled)continue;const due=new Date(a.snoozed_until??a.alarm_at).getTime();if(due>now)continue;const key="pos:alarm:"+a.id+":"+Math.floor(due/60000);if(localStorage.getItem(key))continue;localStorage.setItem(key,"1");if(Notification.permission==="granted")new Notification("⏰ "+a.title,{body:a.description??"Alarma de Personal OS",tag:a.id});if(a.repeat_rule==="once")void personalDomainsService.update("alarms",a.id,{enabled:false,last_fired_at:new Date().toISOString(),snoozed_until:null});else{const next=new Date(due);next.setDate(next.getDate()+(a.repeat_rule==="weekly"?7:1));void personalDomainsService.update("alarms",a.id,{alarm_at:next.toISOString(),last_fired_at:new Date().toISOString(),snoozed_until:null});}}};tick();const id=window.setInterval(tick,15000);return()=>window.clearInterval(id)},[q.data]);
 const add=async()=>{if(!user?.id||!title.trim()||!when)return;const created=await m.create.mutateAsync({user_id:user.id,title:title.trim(),description:description.trim()||null,alarm_at:new Date(when).toISOString(),repeat_rule:repeat}); await lifeGraphService.create("notification_jobs",{source_type:"alarm",source_id:created.id,fire_at:new Date(when).toISOString(),title:"⏰ "+title.trim(),body:description.trim()||null,payload:{repeat_rule:repeat},status:"pending"});setTitle("");setDescription("");setWhen("");setRepeat("once")};
 const sorted=useMemo(()=>[...(q.data??[])].sort((a,b)=>new Date(a.alarm_at).getTime()-new Date(b.alarm_at).getTime()),[q.data]);
 return <div className="space-y-5 pb-24"><GlobalDateHeader/><div className="flex items-center gap-2"><div><h1 className="text-xl font-semibold">Alarmas</h1><p className="text-sm text-muted-foreground">Recordatorios persistentes del dominio Vida.</p></div><HelpTip helpKey="life.alarms"/></div>
 <section className="glass space-y-3 rounded-2xl p-4"><div className="flex items-center gap-2"><Plus className="h-4 w-4"/><h2 className="font-semibold">Nueva alarma</h2><HelpTip helpKey="life.alarms"/></div><Input placeholder="Qué quieres recordar" value={title} onChange={e=>setTitle(e.target.value)}/><RichTextEditor value={description} onChange={setDescription} placeholder="Nota opcional"/><div className="grid gap-2 sm:grid-cols-2"><Input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3" value={repeat} onChange={e=>setRepeat(e.target.value)}><option value="once">Una vez</option><option value="daily">Diaria</option><option value="weekly">Semanal</option></select></div><div className="flex flex-wrap gap-2"><Button onClick={()=>void add()} disabled={m.create.isPending||!title.trim()||!when}><Bell className="mr-2 h-4 w-4"/>Crear alarma</Button>{permission==="default"&&<Button variant="outline" onClick={()=>void Notification.requestPermission().then(setPermission)}>Activar notificaciones</Button>}</div><p className="text-xs text-muted-foreground">Las alarmas se registran en el planificador unificado. Con notificaciones push configuradas en el servidor, siguen funcionando aunque cierres Personal OS.</p></section>
 {sorted.length===0?<EmptyState icon={<BellOff className="h-6 w-6"/>} title="No tienes alarmas" description="Crea una alarma para no depender de la memoria."/>:<div className="space-y-2">{sorted.map(a=><article key={a.id} className={cn("glass rounded-2xl p-4",!a.enabled&&"opacity-55")}><div className="flex items-start gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-primary/10"><Clock className="h-4 w-4"/></div><div className="min-w-0 flex-1"><h3 className="font-medium">{a.title}</h3><p className="text-sm text-muted-foreground">{new Date(a.snoozed_until??a.alarm_at).toLocaleString()} · {a.repeat_rule==="once"?"Una vez":a.repeat_rule==="daily"?"Diaria":"Semanal"}</p>{a.description&&<p className="mt-1 text-xs text-muted-foreground">{a.description}</p>}</div><Button size="icon" variant="ghost" onClick={()=>void m.update.mutateAsync({id:a.id,patch:{enabled:!a.enabled}})} aria-label={a.enabled?"Desactivar":"Activar"}><Check className={cn("h-4 w-4",a.enabled?"text-primary":"text-muted-foreground")}/></Button><Button size="icon" variant="ghost" onClick={()=>void m.remove.mutateAsync(a.id)} aria-label="Eliminar alarma"><Trash2 className="h-4 w-4 text-destructive"/></Button></div></article>)}</div>}
 </div>}
