import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Brain,BookOpen,HeartHandshake,BriefcaseBusiness,Church,ShoppingCart,Trophy,Plus,Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { GlobalDateHeader } from "@/components/common/GlobalDateHeader";
import { HelpTip } from "@/components/common/HelpTip";
import { useAuth } from "@/hooks/use-auth";
import { usePersonalList,usePersonalMutations,usePersonalSummary,useGamification } from "@/hooks/use-personal-domains";
export const Route=createFileRoute("/_authenticated/modulos")({component:ModulesPage});
const tabs=[["mercado","Mercado",ShoppingCart],["aprendizaje","Aprendizaje",BookOpen],["relaciones","Relaciones",HeartHandshake],["trabajo","Trabajo",BriefcaseBusiness],["espiritualidad","Espiritualidad",Church],["ia","IA Personal",Brain],["gamificacion","Gamificación",Trophy]] as const;
const cfg:any={mercado:{table:"shopping_items",title:"Lista de mercado",placeholder:"Producto o artículo",help:"life.shopping"},aprendizaje:{table:"learning_items",title:"Aprendizaje",placeholder:"Curso, libro, idioma, ajedrez o certificación",help:"learning"},relaciones:{table:"relationships",title:"Relaciones importantes",placeholder:"Persona",help:"relationships"},trabajo:{table:"work_items",title:"Trabajo",placeholder:"Tarea, proyecto o idea",help:"work"},espiritualidad:{table:"spiritual_entries",title:"Espiritualidad",placeholder:"Reflexión, oración, lectura o meta",help:"spirituality"}};
function ModulesPage(){const [tab,setTab]=useState<string>("mercado");return <div className="space-y-5 pb-24"><GlobalDateHeader/><div><h1 className="text-xl font-semibold">Módulos personales</h1><p className="text-sm text-muted-foreground">Dominios reales del Life Graph.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={"rounded-xl border px-2 py-3 text-left text-xs "+(tab===id?"border-primary bg-primary/10":"border-border")}><Icon className="mb-1 h-4 w-4"/>{label}</button>)}</div>{tab==="ia"?<PersonalAI/>:tab==="gamificacion"?<Gamification/>:<DomainCrud kind={tab as keyof typeof cfg}/>}</div>}
function DomainCrud({kind}:{kind:keyof typeof cfg}){const c=cfg[kind];const {user}=useAuth();const q=usePersonalList<any>(c.table,"created_at");const m=usePersonalMutations(c.table);const [name,setName]=useState("");const [note,setNote]=useState("");const add=async()=>{if(!user?.id||!name.trim())return;let x:any={user_id:user.id};if(kind==="mercado")x={...x,name:name.trim(),list_name:"Mercado",note:note.trim()||null};if(kind==="aprendizaje")x={...x,title:name.trim(),kind:"course",notes:note.trim()||null};if(kind==="relaciones")x={...x,name:name.trim(),notes:note.trim()||null};if(kind==="trabajo")x={...x,title:name.trim(),kind:"task",notes:note.trim()||null};if(kind==="espiritualidad")x={...x,entry_date:new Date().toISOString().slice(0,10),title:name.trim(),content:note.trim()||null};await m.create.mutateAsync(x);setName("");setNote("")};return <section className="glass space-y-3 rounded-2xl p-4"><div className="flex items-center gap-2"><h2 className="font-semibold">{c.title}</h2><HelpTip helpKey={c.help}/></div><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input value={name} onChange={e=>setName(e.target.value)} placeholder={c.placeholder}/><Input value={note} onChange={e=>setNote(e.target.value)} placeholder="Nota opcional"/><Button onClick={()=>void add()} disabled={m.create.isPending||!name.trim()}><Plus className="mr-1 h-4 w-4"/>Agregar</Button></div>{q.isLoading?<p className="text-sm text-muted-foreground">Cargando…</p>:<div className="space-y-2">{(q.data??[]).map((item:any)=><div key={item.id} className="flex items-center gap-2 rounded-xl border border-border/60 px-3 py-2"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.name??item.title}</p><p className="truncate text-xs text-muted-foreground">{item.notes??item.note??item.content??""}</p></div><Button size="icon" variant="ghost" onClick={()=>void m.remove.mutateAsync(item.id)} aria-label="Eliminar"><Trash2 className="h-4 w-4 text-destructive"/></Button></div>)}</div>}</section>}
function PersonalAI(){const s=usePersonalSummary();return <section className="glass space-y-4 rounded-2xl p-5"><div className="flex items-center gap-2"><Brain className="h-5 w-5"/><h2 className="font-semibold">IA Personal</h2><HelpTip helpKey="ai.personal"/></div><p className="text-sm text-muted-foreground">Capa analítica determinista: observa el Life Graph real, sin inventar datos ni requerir una API externa.</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{Object.entries(s.data??{}).map(([k,v])=><div key={k} className="rounded-xl border border-border p-3"><p className="text-xs capitalize text-muted-foreground">{k.replaceAll("_"," ")}</p><p className="text-xl font-semibold">{v}</p></div>)}</div><p className="text-sm">La siguiente capa puede convertir estas señales en tendencias, riesgos y recomendaciones explicables.</p></section>}
function Gamification(){const g=useGamification();return <section className="glass space-y-4 rounded-2xl p-5"><div className="flex items-center gap-2"><Trophy className="h-5 w-5"/><h2 className="font-semibold">Gamificación</h2><HelpTip helpKey="gamification"/></div><p className="text-sm text-muted-foreground">XP y niveles persistentes. No penaliza días malos.</p><div className="rounded-xl border p-4"><p className="text-3xl font-bold">{g.query.data?.xp??0} XP</p><p className="text-sm text-muted-foreground">Nivel {g.query.data?.level??1}</p></div><Button variant="outline" onClick={()=>void g.mutation.mutateAsync(g.query.data?.xp??0)}>Guardar estado</Button></section>}
