import { useEffect,useRef,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ChevronDown,ChevronUp,Download,GripVertical,Loader2,RefreshCw,Save,RotateCcw,Upload } from "lucide-react";
import { Avatar,AvatarFallback,AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Switch } from "@/components/ui/switch";
import { HelpTip } from "@/components/common/HelpTip"; import { NAV_ITEMS } from "@/components/shell/nav-items"; import { cn } from "@/lib/utils";
import { useAuth } from "@/hooks/use-auth"; import { useProfile,useProfileMediaUrl,useProfileMutations } from "@/hooks/use-profile"; import { useHelpEnabled,useSetHelpEnabled } from "@/hooks/use-help"; import { useTheme,type ThemeName } from "@/hooks/use-theme"; import { requestNotificationPermission } from "@/hooks/use-medication-reminders";
import { lifeGraphService } from "@/services/life-graph.service";
export const Route=createFileRoute("/_authenticated/perfil")({component:ProfilePage});
const DEFAULT_ORDER=NAV_ITEMS.map(x=>x.key);
const FEATURE_LABELS:[string,string][]=[["spirituality.fasting","Espiritualidad → Ayuno"],["spirituality.prophecy","Espiritualidad → Profecía"],["health.cycle","Salud → Registro menstrual"],["health.nutrition","Salud → Nutrición"],["health.appointments","Salud → Citas médicas"],["learning.books","Aprendizaje → Libros"]];
const WIDGETS:[string,string][]=[["daily","Resumen del día"],["goals","Metas"],["ai","Señales de IA"],["finance","Finanzas"],["health","Salud"],["learning","Aprendizaje"]];
const BACKUP_TABLES=["profiles","habits","habit_logs","habit_categories","planner_items","planner_categories","finance_accounts","finance_categories","finance_transactions","finance_settings","journal_entries","alarms","health_metrics","medications","medication_doses","shopping_lists","shopping_items","life_goals","routines","routine_logs","checklists","checklist_items","bucket_list","menstrual_profiles","menstrual_records","medical_appointments","nutrition_logs","learning_items","learning_notes","learning_sessions","language_profiles","relationships","relationship_interactions","work_items","work_sessions","spiritual_entries","gamification_achievements","gamification_challenges","life_events","notification_jobs","ai_runs","finance_budgets","finance_debts","finance_savings_goals","finance_investments","finance_external_sources","finance_external_snapshots"] as const;
function ProfilePage(){
 const{user}=useAuth();const pq=useProfile();const{save,uploadMedia}=useProfileMutations();const help=useHelpEnabled();const setHelp=useSetHelpEnabled();const{theme,setTheme}=useTheme();
 const[name,setName]=useState(""),[avatar,setAvatar]=useState<string|null>(null),[background,setBackground]=useState<string|null>(null),[order,setOrder]=useState(DEFAULT_ORDER),[hidden,setHidden]=useState<string[]>([]),[features,setFeatures]=useState<Record<string,boolean>>({}),[widgets,setWidgets]=useState<string[]>(["daily","goals","ai","finance"]),[privacy,setPrivacy]=useState(true),[push,setPush]=useState(false),[busy,setBusy]=useState(false),[importing,setImporting]=useState(false),[relationshipNotifications,setRelationshipNotifications]=useState(true);
 const ar=useRef<HTMLInputElement>(null),br=useRef<HTMLInputElement>(null),ir=useRef<HTMLInputElement>(null);
 const p=pq.data;
 useEffect(()=>{if(!p)return;setName(p.display_name||p.full_name||"");setAvatar(p.avatar_url);setBackground(p.background_url);setOrder(p.module_order?.length?p.module_order:DEFAULT_ORDER);setHidden(p.hidden_modules||[]);setFeatures(p.hidden_features||{});setWidgets(p.dashboard_widgets?.length?p.dashboard_widgets:["daily","goals","ai","finance"]);setPrivacy(p.notification_preferences?.privacy?.allow_external_ai!==false);setRelationshipNotifications(p.notification_preferences?.relationships!==false)},[p]);
 const au=useProfileMediaUrl(avatar).data;const bu=useProfileMediaUrl(background&&!background.startsWith("#")?background:null).data;
 const pick=async(file:File|undefined,kind:"avatar"|"background")=>{if(!file)return;setBusy(true);try{const path=await uploadMedia.mutateAsync({file,kind});if(kind==="avatar")setAvatar(path);else setBackground(path)}finally{setBusy(false)}};
 const move=(i:number,d:number)=>setOrder(a=>{const b=[...a],j=i+d;if(j<0||j>=b.length)return a;[b[i],b[j]]=[b[j],b[i]];return b});
 const saveAll=async()=>{await save.mutateAsync({display_name:name.trim()||null,full_name:name.trim()||null,avatar_url:avatar,background_url:background,module_order:order,hidden_modules:hidden,hidden_features:features,dashboard_widgets:widgets,notification_preferences:{...(p?.notification_preferences||{}),privacy:{allow_external_ai:privacy},relationships:{enabled:prefsEnabled}}})};
 
 const exportBackup=async()=>{const entries=await Promise.all(BACKUP_TABLES.map(async t=>[t,await lifeGraphService.list(t as any)] as const));const blob=new Blob([JSON.stringify({format:"personal-os-backup-v1",exported_at:new Date().toISOString(),user_id:user?.id,data:Object.fromEntries(entries)},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="personal-os-backup.json";a.click();URL.revokeObjectURL(a.href)};
 const importBackup=async(file:File|undefined)=>{if(!file)return;setImporting(true);try{const payload=JSON.parse(await file.text());if(payload.user_id&&payload.user_id!==user?.id)throw new Error("Este respaldo pertenece a otro usuario.");await lifeGraphService.importBackup(payload.data||{},BACKUP_TABLES as unknown as string[]);await pq.refetch()}catch(e){window.alert(e instanceof Error?e.message:"No se pudo importar el respaldo")}finally{setImporting(false)}};
 if(pq.isLoading)return <Loader2 className="animate-spin"/>;
 return <div className="space-y-5 pb-24">
  <div><div className="flex items-center gap-2"><h1 className="text-xl font-semibold">Perfil y configuración</h1><HelpTip helpKey="profile"/></div><p className="text-sm text-muted-foreground">Todo lo que personaliza tu Personal OS vive aquí.</p></div>
  <section className="glass space-y-4 rounded-2xl p-4"><h2 className="font-semibold">Identidad y apariencia</h2><div className="flex items-center gap-4"><Avatar className="h-16 w-16"><AvatarImage src={au||undefined}/><AvatarFallback>{(name||"PS").slice(0,2).toUpperCase()}</AvatarFallback></Avatar><Button variant="outline" size="sm" disabled={busy} onClick={()=>ar.current?.click()}><Upload className="mr-1 h-4 w-4"/>Foto</Button><input ref={ar} type="file" accept="image/*" hidden onChange={e=>void pick(e.target.files?.[0],"avatar")}/></div><Label>Nombre</Label><Input value={name} onChange={e=>setName(e.target.value)}/><div className="flex flex-wrap items-center gap-2"><Button size="sm" variant={theme==="dark"?"default":"outline"} onClick={()=>setTheme("dark" as ThemeName)}>Oscuro</Button><Button size="sm" variant={theme==="light"?"default":"outline"} onClick={()=>setTheme("light" as ThemeName)}>Claro</Button><Button size="sm" variant="outline" disabled={busy} onClick={()=>br.current?.click()}><Upload className="mr-1 h-4 w-4"/>Fondo</Button><input ref={br} type="file" accept="image/*" hidden onChange={e=>void pick(e.target.files?.[0],"background")}/>{bu&&<span className="text-xs text-muted-foreground">Fondo cargado</span>}</div><div className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm font-medium">Ayudas contextuales</span><Switch checked={help} onCheckedChange={v=>setHelp.mutate(v)}/></div></section>
  <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">Sidebar: orden y módulos visibles</h2><p className="text-xs text-muted-foreground">Tu orden y visibilidad son por usuario.</p>{order.map((key,i)=>{const item=NAV_ITEMS.find(x=>x.key===key);if(!item)return null;const visible=!hidden.includes(key);return <div key={key} className={cn("flex items-center gap-2 rounded-xl border p-2",!visible&&"opacity-50")}><GripVertical className="h-4 w-4 text-muted-foreground"/><span className="flex-1 text-sm">{item.label}</span><Switch checked={visible} onCheckedChange={v=>setHidden(h=>v?h.filter(x=>x!==key):[...h,key])}/><Button size="icon" variant="ghost" disabled={i===0} onClick={()=>move(i,-1)}><ChevronUp className="h-4 w-4"/></Button><Button size="icon" variant="ghost" disabled={i===order.length-1} onClick={()=>move(i,1)}><ChevronDown className="h-4 w-4"/></Button></div>})}<Button variant="outline" onClick={()=>{setOrder(DEFAULT_ORDER);setHidden([])}}><RotateCcw className="mr-1 h-4 w-4"/>Restablecer</Button></section>
  <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">Funciones opcionales</h2>{FEATURE_LABELS.map(([key,label])=><div key={key} className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">{label}</span><Switch checked={features[key]!==true} onCheckedChange={v=>setFeatures(f=>({...f,[key]:!v}))}/></div>)}</section>
  <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">Inicio y widgets</h2>{WIDGETS.map(([key,label])=><div key={key} className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">{label}</span><Switch checked={widgets.includes(key)} onCheckedChange={v=>setWidgets(w=>v?w.includes(key)?w:[...w,key]:w.filter(x=>x!==key))}/></div>)}</section>
  <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">Notificaciones y privacidad</h2><div className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">Cumpleaños/aniversarios y citas médicas</span><Switch checked={relationshipNotifications} onCheckedChange={setRelationshipNotifications}/></div><div className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">Permitir análisis externo de datos</span><Switch checked={privacy} onCheckedChange={setPrivacy}/></div><p className="text-xs text-muted-foreground">La IA de Personal OS usa señales locales del Life Graph. Esta opción queda reservada para futuras conexiones externas.</p><Button variant="outline" onClick={()=>void requestNotificationPermission().then(p=>setPush(p==="granted"))}><RefreshCw className="mr-1 h-4 w-4"/>Activar notificaciones en segundo plano</Button></section>
  <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">WíswellArt → Finanzas</h2><p className="text-sm text-muted-foreground">La integración admite exactamente dos valores por período: ingresos y egresos, guardados como snapshot externo. Esto separa la contabilidad de WíswellArt del libro mayor personal.</p><div className="rounded-xl border p-3 font-mono text-xs break-all">POST /api/integrations/wiswellart<br/>x-pos-integration-secret<br/>{"{period_start, period_end, income, expense}"}</div></section>
  <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">Exportar / importar / backup</h2><div className="flex flex-wrap gap-2"><Button onClick={()=>void exportBackup()}><Download className="mr-1 h-4 w-4"/>Exportar JSON</Button><Button variant="outline" disabled={importing} onClick={()=>ir.current?.click()}>{importing?<Loader2 className="mr-1 h-4 w-4 animate-spin"/>:<Upload className="mr-1 h-4 w-4"/>}Importar JSON</Button><input ref={ir} type="file" accept="application/json" hidden onChange={e=>void importBackup(e.target.files?.[0])}/></div><p className="text-xs text-muted-foreground">La importación valida el usuario del respaldo y hace upsert por ID, sin borrar datos existentes.</p></section>
  <div className="flex justify-end"><Button onClick={()=>void saveAll()} disabled={save.isPending}><Save className="mr-1 h-4 w-4"/>{save.isPending?"Guardando…":"Guardar configuración"}</Button></div>
 </div>
}
