import { useEffect,useMemo,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2,Clock3,FolderKanban,Lightbulb,Pause,Play,Plus,SquareCheck,Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { RichTextEditor } from "@/components/common/RichTextEditor";
import { GlobalDateHeader } from "@/components/common/GlobalDateHeader";
import { HelpTip } from "@/components/common/HelpTip";
import { useGlobalDate } from "@/hooks/use-global-date";
import { useAuth } from "@/hooks/use-auth";
import { useLGList,useLGMutations } from "@/hooks/use-life-graph"; import { lifeGraphService } from "@/services/life-graph.service";
export const Route=createFileRoute("/_authenticated/trabajo")({component:WorkPage});
function WorkPage(){
 const{date}=useGlobalDate();const{user}=useAuth();const items=useLGList("work_items");const sessions=useLGList("work_sessions","session_date");const im=useLGMutations("work_items");const sm=useLGMutations("work_sessions");const cm=useLGMutations("checklists");const cim=useLGMutations("checklist_items");const cqs=useLGList("checklists");
 const[projectName,setProjectName]=useState(""),[projectNotes,setProjectNotes]=useState(""),[due,setDue]=useState(""),[selected,setSelected]=useState<string>(()=>typeof window==="undefined"?"":new URLSearchParams(window.location.search).get("project")||""),[task,setTask]=useState(""),[taskNotes,setTaskNotes]=useState(""),[checkTitle,setCheckTitle]=useState(""),[selectedChecklist,setSelectedChecklist]=useState<string>(""),[checkItem,setCheckItem]=useState(""),[idea,setIdea]=useState(""),[timerRefresh,setTimerRefresh]=useState(0);
 const all=items.data||[];const projects=all.filter((x:any)=>x.kind==="project");const tasks=all.filter((x:any)=>x.kind==="task");const active=(sessions.data||[]).find((x:any)=>x.status==="active");const activeProject=active?all.find((x:any)=>x.id===active.work_item_id):null;
 const projectTasks=selected?tasks.filter((x:any)=>x.parent_work_item_id===selected):[];
 const selectedProject=projects.find((x:any)=>x.id===selected);
 const checklistItems=useLGList("checklist_items","position"); const selectedChecks=(cqs.data||[]).filter((x:any)=>x.linked_id===selected);
 const todaysMinutes=(sessions.data||[]).filter((x:any)=>x.session_date===date&&x.status!=="active").reduce((a:any,x:any)=>a+Number(x.minutes||0),0);
 const activeMinutes=active?.started_at?Math.max(0,Math.floor((Date.now()-new Date(active.started_at).getTime())/60000)+timerRefresh*0):0;
 const createProject=async()=>{if(!projectName.trim())return;const p=await im.create.mutateAsync({user_id:user?.id,title:projectName.trim(),kind:"project",status:"open",target_date:due||null,notes:projectNotes||null});setProjectName("");setProjectNotes("");setDue("");setSelected(p.id)};
 const createTask=async()=>{if(!selected||!task.trim())return;const created=await im.create.mutateAsync({user_id:user?.id,title:task.trim(),kind:"task",status:"open",parent_work_item_id:selected,notes:taskNotes||null}); await lifeGraphService.link("work_item",selected,"work_item",created.id,"contains_task"); setTask("");setTaskNotes("")};
 const createChecklist=async()=>{if(!selected||!checkTitle.trim())return;const c=await cm.create.mutateAsync({user_id:user?.id,title:checkTitle.trim(),linked_type:"work_item",linked_id:selected});setCheckTitle("");setSelectedChecklist(c.id)};
 const addChecklistItem=async()=>{if(!selectedChecklist||!checkItem.trim())return;await cim.create.mutateAsync({user_id:user?.id,checklist_id:selectedChecklist,title:checkItem.trim(),position:((cqs.data||[]).filter((x:any)=>x.id===selectedChecklist)[0]?.item_count)||0});setCheckItem("")};
 const start=async()=>{if(!selectedProject){toast.error("Selecciona un proyecto");return}if(active){toast.error("Ya hay un bloque de trabajo activo");return}const started=new Date().toISOString();const session=await sm.create.mutateAsync({user_id:user?.id,work_item_id:selectedProject.id,session_date:date,minutes:0,notes:null,started_at:started,status:"active",target_minutes:50,ended_at:null}); await lifeGraphService.link("work_session",session.id,"work_item",selectedProject.id,"worked_on");setTimerRefresh(v=>v+1)};
 const stop=async()=>{if(!active)return;await sm.update.mutateAsync({id:active.id,patch:{ended_at:new Date().toISOString(),status:"completed"}});setTimerRefresh(v=>v+1)};
 return <div className="space-y-5 pb-24"><GlobalDateHeader/><header><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold">Trabajo</h1><HelpTip helpKey="work"/></div><p className="text-sm text-muted-foreground">Ideas, proyectos, tareas, checklists y tiempo trabajado viven juntos. El Diario puede alimentar este módulo sin duplicar información.</p></header>
 <section className="grid gap-3 md:grid-cols-[1.2fr_.8fr]"><div className="glass space-y-4 rounded-3xl p-5"><div className="flex items-center gap-2"><Lightbulb className="h-5 w-5"/><h2 className="font-semibold">Nueva idea de trabajo</h2></div><Input placeholder="Título breve" value={idea} onChange={e=>setIdea(e.target.value)}/><RichTextEditor value={projectNotes} onChange={setProjectNotes} placeholder="Desarrolla la idea, problema, solución, funciones, dudas…"/><Button disabled={!idea.trim()} onClick={()=>{setProjectName(idea);setIdea("");}}><FolderKanban className="mr-1 h-4 w-4"/>Preparar como proyecto</Button></div><div className="glass space-y-3 rounded-3xl p-5"><div className="flex items-center gap-2"><Clock3 className="h-5 w-5"/><h2 className="font-semibold">Tiempo</h2></div>{active?<><p className="text-sm">Trabajando en <b>{activeProject?.title||"proyecto"}</b></p><p className="text-4xl font-semibold tabular-nums">{activeMinutes}<span className="ml-1 text-base font-normal text-muted-foreground">min</span></p><p className="text-xs text-muted-foreground">El bloque se registrará con su hora real de inicio y fin.</p><Button variant="outline" onClick={()=>void stop()}><Pause className="mr-1 h-4 w-4"/>Terminar bloque</Button></>:<><p className="text-3xl font-semibold">{todaysMinutes}<span className="ml-1 text-base font-normal text-muted-foreground">min hoy</span></p><p className="text-xs text-muted-foreground">Iniciar un bloque programa automáticamente una alerta de descanso al llegar al límite.</p></>}</div></section>
 <section className="glass space-y-3 rounded-3xl p-5"><div className="flex items-center gap-2"><FolderKanban className="h-5 w-5"/><h2 className="font-semibold">Crear proyecto</h2></div><div className="grid gap-2 sm:grid-cols-[1fr_160px_auto]"><Input placeholder="Nombre del proyecto" value={projectName} onChange={e=>setProjectName(e.target.value)}/><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/><Button disabled={!projectName.trim()} onClick={()=>void createProject()}><Plus className="mr-1 h-4 w-4"/>Crear</Button></div><RichTextEditor value={projectNotes} onChange={setProjectNotes} placeholder="Descripción, alcance, objetivos…"/></section>
 <div className="grid gap-4 lg:grid-cols-[1fr_1.2fr]"><section className="space-y-3"><h2 className="font-semibold">Proyectos</h2>{projects.length===0?<div className="glass rounded-2xl border-dashed p-5 text-sm text-muted-foreground">Todavía no hay proyectos. Una idea del Diario puede convertirse aquí.</div>:projects.map((p:any)=>{const mins=(sessions.data||[]).filter((s:any)=>s.work_item_id===p.id).reduce((a:any,s:any)=>a+Number(s.minutes||0),0);return <button key={p.id} type="button" onClick={()=>setSelected(p.id)} className={"w-full rounded-2xl border p-4 text-left "+(selected===p.id?"border-primary bg-primary/5":"border-border") }><div className="flex items-start gap-3"><FolderKanban className="mt-0.5 h-4 w-4"/><div className="min-w-0 flex-1"><p className="font-medium">{p.title}</p><p className="text-xs text-muted-foreground">{p.target_date?"Fecha objetivo "+p.target_date:"Sin fecha"} · {mins} min registrados</p></div></div></button>})}</section>
 <section className="space-y-4">{selectedProject?<><div className="glass rounded-2xl p-4"><div className="flex items-center justify-between gap-2"><div><p className="text-xs uppercase tracking-wide text-muted-foreground">Proyecto seleccionado</p><h2 className="text-lg font-semibold">{selectedProject.title}</h2></div><Button size="sm" onClick={()=>active?void stop():void start()}>{active?<><Pause className="mr-1 h-4 w-4"/>Parar</>:<><Play className="mr-1 h-4 w-4"/>Iniciar 50 min</>}</Button></div></div><section className="glass space-y-3 rounded-2xl p-4"><h3 className="font-semibold">Tareas</h3><div className="flex gap-2"><Input placeholder="Nueva tarea" value={task} onChange={e=>setTask(e.target.value)}/><Button disabled={!task.trim()} onClick={()=>void createTask()}><Plus className="h-4 w-4"/></Button></div><RichTextEditor value={taskNotes} onChange={setTaskNotes} placeholder="Contexto de la tarea…"/>{projectTasks.length===0?<p className="text-sm text-muted-foreground">No hay tareas todavía.</p>:projectTasks.map((t:any)=><div key={t.id} className="flex items-center gap-2 rounded-xl border p-3"><CheckCircle2 className="h-4 w-4 text-muted-foreground"/><span className="flex-1 text-sm">{t.title}</span><Button size="icon" variant="ghost" onClick={()=>void im.remove.mutateAsync(t.id)}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>)}</section><section className="glass space-y-3 rounded-2xl p-4"><div className="flex items-center gap-2"><SquareCheck className="h-4 w-4"/><h3 className="font-semibold">Checklists</h3></div><div className="flex gap-2"><Input placeholder="Nombre del checklist" value={checkTitle} onChange={e=>setCheckTitle(e.target.value)}/><Button disabled={!checkTitle.trim()} onClick={()=>void createChecklist()}><Plus className="h-4 w-4"/></Button></div>{selectedChecks.map((c:any)=><button key={c.id} type="button" onClick={()=>setSelectedChecklist(c.id)} className={"block w-full rounded-xl border p-3 text-left text-sm "+(selectedChecklist===c.id?"border-primary bg-primary/5":"border-border")}>{c.title}</button>)}{selectedChecklist&&<div className="space-y-2 rounded-xl border p-3"><div className="flex gap-2"><Input placeholder="Objetivo / elemento" value={checkItem} onChange={e=>setCheckItem(e.target.value)}/><Button disabled={!checkItem.trim()} onClick={()=>void addChecklistItem()}><Plus className="h-4 w-4"/></Button></div>{(checklistItems.data||[]).filter((i:any)=>i.checklist_id===selectedChecklist).map((i:any)=><div key={i.id} className="flex items-center gap-2 rounded-lg border px-2 py-1.5 text-xs"><input type="checkbox" checked={Boolean(i.completed)} onChange={e=>void cim.update.mutateAsync({id:i.id,patch:{completed:e.target.checked}})}/><span>{i.title}</span></div>)}</div>}</section></>:<div className="glass rounded-2xl border-dashed p-6 text-sm text-muted-foreground">Selecciona un proyecto para ver sus tareas, checklists y tiempo.</div>}</section></div></div>;
}
