import type { ReactNode } from "react";
import { useState } from "react";
import { HeartHandshake, BriefcaseBusiness, Church, Plus, Trash2, Clock3, Pencil, X, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { RichTextEditor } from "@/components/common/RichTextEditor";
import { HelpTip } from "@/components/common/HelpTip";
import { useLGList, useLGMutations } from "@/hooks/use-life-graph";
import { useAuth } from "@/hooks/use-auth";
import { useGlobalDate } from "@/hooks/use-global-date";
import { useProfile } from "@/hooks/use-profile";

export function RelationshipsPage() {
  const q = useLGList("relationships");
  const m = useLGMutations("relationships");
  const ints = useLGList("relationship_interactions", "interaction_on");
  const im = useLGMutations("relationship_interactions");
  const { user } = useAuth();
  const { date } = useGlobalDate();
  const [name,setName]=useState(""),[type,setType]=useState("pareja"),[birthday,setBirthday]=useState(""),[anniversary,setAnniversary]=useState(""),[next,setNext]=useState(""),[frequency,setFrequency]=useState(""),[notes,setNotes]=useState("");
  const [selected,setSelected]=useState<any>(null),[interaction,setInteraction]=useState(""),[interactionType,setInteractionType]=useState("contact");
  const reset=()=>{setName("");setType("pareja");setBirthday("");setAnniversary("");setNext("");setFrequency("");setNotes("");setSelected(null)};
  const startEdit=(r:any)=>{setSelected(r);setName(r.name||"");setType(r.relationship_type||"importante");setBirthday(r.birthday||"");setAnniversary(r.anniversary||"");setNext(r.next_contact_on||"");setFrequency(r.contact_frequency_days?String(r.contact_frequency_days):"");setNotes(r.notes||"");};
  return <PageShell icon={<HeartHandshake className="h-5 w-5"/>} title="Relaciones" subtitle="Personas importantes, no una agenda de contactos: cuidado, fechas, seguimiento e historial.">
    <section className="glass space-y-3 rounded-2xl p-4">
      <div className="flex items-center justify-between"><h2 className="font-semibold">{selected ? "Editar relación" : "Nueva relación"}</h2>{selected&&<Button size="sm" variant="ghost" onClick={reset}><X className="mr-1 h-4 w-4"/>Cancelar</Button>}</div>
      <div className="grid gap-2 sm:grid-cols-4">
        <Input placeholder="Nombre" value={name} onChange={e=>setName(e.target.value)}/>
        <select className="h-10 rounded-md border bg-background px-3" value={type} onChange={e=>setType(e.target.value)}><option>pareja</option><option>familia</option><option>hijo/a</option><option>amigo/a</option><option>importante</option></select>
        <Input type="date" aria-label="Cumpleaños" value={birthday} onChange={e=>setBirthday(e.target.value)}/>
        <Input type="date" aria-label="Aniversario" value={anniversary} onChange={e=>setAnniversary(e.target.value)}/>
      </div>
      <div className="grid gap-2 sm:grid-cols-2">
        <Input type="date" aria-label="Próximo contacto" value={next} onChange={e=>setNext(e.target.value)}/>
        <Input type="number" min="1" placeholder="Frecuencia de contacto (días)" value={frequency} onChange={e=>setFrequency(e.target.value)}/>
      </div>
      <RichTextEditor value={notes} onChange={setNotes} placeholder="Notas sobre la relación, contexto, cosas importantes…"/>
      <Button disabled={!name.trim()} onClick={()=>void (selected ? m.update.mutateAsync({id:selected.id,patch:{name:name.trim(),relationship_type:type,birthday:birthday||null,anniversary:anniversary||null,next_contact_on:next||null,contact_frequency_days:Number(frequency)||null,notes:notes||null}}) : m.create.mutateAsync({user_id:user?.id,name:name.trim(),relationship_type:type,birthday:birthday||null,anniversary:anniversary||null,next_contact_on:next||null,contact_frequency_days:Number(frequency)||null,notes:notes||null})).then(reset)}>
        {selected?<><CheckCircle2 className="mr-1 h-4 w-4"/>Guardar cambios</>:<><Plus className="mr-1 h-4 w-4"/>Agregar persona</>}
      </Button>
    </section>
    {(q.data||[]).map((r:any)=>{const ri=(ints.data||[]).filter((x:any)=>x.relationship_id===r.id);return <article key={r.id} className="glass space-y-3 rounded-2xl p-4">
      <div className="flex gap-2"><div className="flex-1"><h2 className="font-semibold">{r.name}</h2><p className="text-xs text-muted-foreground">{r.relationship_type||"Importante"}{r.birthday?" · cumpleaños "+r.birthday:""}{r.anniversary?" · aniversario "+r.anniversary:""}{r.next_contact_on?" · seguimiento "+r.next_contact_on:""}{r.contact_frequency_days?" · cada "+r.contact_frequency_days+" días":""}</p></div><Button size="icon" variant="ghost" onClick={()=>startEdit(r)}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={()=>void m.remove.mutateAsync(r.id)}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>
      <Button size="sm" variant="outline" onClick={()=>{setSelected(r);setInteraction("");setInteractionType("contact")}}>Registrar interacción</Button>
      {selected?.id===r.id&&<div className="space-y-2 rounded-xl border p-3"><div className="grid gap-2 sm:grid-cols-2"><Input type="date" value={date} readOnly/><select className="h-10 rounded-md border bg-background px-3" value={interactionType} onChange={e=>setInteractionType(e.target.value)}><option value="contact">Contacto</option><option value="conversation">Conversación</option><option value="visit">Visita</option><option value="help">Ayuda</option><option value="important">Momento importante</option></select></div><RichTextEditor value={interaction} onChange={setInteraction} placeholder="Qué hablaron, hicieron, cómo quedó la relación…"/><div className="flex gap-2"><Button size="sm" onClick={()=>void im.create.mutateAsync({user_id:user?.id,relationship_id:r.id,interaction_on:date,interaction_type:interactionType,notes:interaction||null}).then(()=>{setInteraction("");setSelected(null)})}>Guardar interacción</Button><Button size="sm" variant="ghost" onClick={()=>setSelected(null)}>Cancelar</Button></div></div>}
      {ri.slice(0,5).map((x:any)=><div key={x.id} className="rounded-xl border px-3 py-2 text-xs"><b>{x.interaction_on}</b> · {x.interaction_type}<div className="prose prose-xs dark:prose-invert" dangerouslySetInnerHTML={{__html:x.notes||""}}/></div>)}
    </article>})}
    <div className="text-xs text-muted-foreground"><HelpTip helpKey="relationships"/> Cumpleaños, aniversarios y seguimientos generan recordatorios persistentes; una interacción puede calcular automáticamente el próximo contacto cuando hay frecuencia definida.</div>
  </PageShell>
}

export function WorkPage(){
  const q=useLGList("work_items");const m=useLGMutations("work_items");const s=useLGList("work_sessions","session_date");const sm=useLGMutations("work_sessions");const{user}=useAuth();const{date}=useGlobalDate();const[title,setTitle]=useState(""),[kind,setKind]=useState("task"),[client,setClient]=useState(""),[due,setDue]=useState(""),[notes,setNotes]=useState(""),[minutes,setMinutes]=useState<Record<string,string>>({}),[project,setProject]=useState("");
  return <PageShell icon={<BriefcaseBusiness className="h-5 w-5"/>} title="Trabajo" subtitle="Tareas, proyectos, reuniones, clientes, tiempo e ideas."><section className="glass space-y-3 rounded-2xl p-4"><div className="grid gap-2 sm:grid-cols-5"><Input placeholder="Título" value={title} onChange={e=>setTitle(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3" value={kind} onChange={e=>setKind(e.target.value)}><option value="task">Tarea</option><option value="project">Proyecto</option><option value="meeting">Reunión</option><option value="idea">Idea</option><option value="goal">Objetivo</option></select><Input placeholder="Proyecto" value={project} onChange={e=>setProject(e.target.value)}/><Input placeholder="Cliente" value={client} onChange={e=>setClient(e.target.value)}/><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></div><RichTextEditor value={notes} onChange={setNotes} placeholder="Descripción, agenda, objetivos…"/><Button disabled={!title.trim()} onClick={()=>void m.create.mutateAsync({user_id:user?.id,title:title.trim(),kind,status:"open",project:project||null,client:client||null,target_date:due||null,notes:notes||null}).then(()=>setTitle(""))}><Plus className="mr-1 h-4 w-4"/>Agregar</Button></section>{(q.data||[]).map((x:any)=><article key={x.id} className="glass rounded-2xl p-4"><div className="flex gap-2"><div className="flex-1"><h2 className="font-semibold">{x.title}</h2><p className="text-xs text-muted-foreground">{x.kind}{x.project?" · "+x.project:""}{x.client?" · "+x.client:""}{x.target_date?" · "+x.target_date:""}</p></div><Button size="icon" variant="ghost" onClick={()=>void m.remove.mutateAsync(x.id)}><Trash2 className="h-4 w-4 text-destructive"/></Button></div><div className="mt-2 flex gap-2"><Input className="w-28" type="number" placeholder="minutos" value={minutes[x.id]||""} onChange={e=>setMinutes(v=>({...v,[x.id]:e.target.value}))}/><Button size="sm" variant="outline" onClick={()=>void sm.create.mutateAsync({user_id:user?.id,work_item_id:x.id,session_date:date,minutes:Number(minutes[x.id])||0,notes:null})}><Clock3 className="mr-1 h-3.5 w-3.5"/>Registrar sesión</Button></div></article>)}<div className="glass rounded-2xl p-4 text-xs text-muted-foreground">Minutos registrados hasta ahora: {(s.data||[]).reduce((a:any,x:any)=>a+Number(x.minutes||0),0)}.</div></PageShell>
}

export function SpiritualityPage(){
  const entries=useLGList("spiritual_entries","entry_date");const em=useLGMutations("spiritual_entries");const goals=useLGList("spiritual_goals");const gm=useLGMutations("spiritual_goals");const{user}=useAuth();const{date}=useGlobalDate();const{data:profile}=useProfile();
  const[title,setTitle]=useState(""),[kind,setKind]=useState("prayer"),[content,setContent]=useState(""),[prophecy,setProphecy]=useState(""),[scripture,setScripture]=useState(""),[answered,setAnswered]=useState(false),[answeredNote,setAnsweredNote]=useState(""),[goalTitle,setGoalTitle]=useState(""),[goalDescription,setGoalDescription]=useState(""),[goalDate,setGoalDate]=useState(""),[goalProgress,setGoalProgress]=useState("0");
  const fastingHidden=profile?.hidden_features?.["spirituality.fasting"]===true;
  const kinds:[string,string][]=[["prayer","Oración"],["reflection","Reflexión"],["gratitude","Gratitud"],["reading","Lectura"],["prophecy","Profecía"]];if(!fastingHidden)kinds.push(["fasting","Ayuno"]);
  const clearEntry=()=>{setTitle("");setKind("prayer");setContent("");setProphecy("");setScripture("");setAnswered(false);setAnsweredNote("")};
  return <PageShell icon={<Church className="h-5 w-5"/>} title="Espiritualidad" subtitle="Módulo opcional y configurable. Registra tu práctica espiritual sin imponer una tradición al sistema.">
    <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">Nuevo registro</h2><div className="grid gap-2 sm:grid-cols-[1fr_180px]"><Input placeholder="Título" value={title} onChange={e=>setTitle(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3" value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div>
      <RichTextEditor value={content} onChange={setContent} placeholder="Escribe aquí tu oración, reflexión, gratitud o lectura…"/>
      {kind==="prophecy"&&<><div className="rounded-xl border p-3 text-sm text-muted-foreground">La profecía queda vinculada a la fecha seleccionada del día. Puedes conservar el texto completo sin convertirlo en una afirmación automática del sistema.</div><RichTextEditor value={prophecy} onChange={setProphecy} placeholder="Texto libre de la profecía recibida…"/></>}
      {kind==="reading"&&<Input placeholder="Referencia de lectura (libro, capítulo, pasaje…)" value={scripture} onChange={e=>setScripture(e.target.value)}/>}
      {kind==="prayer"&&<div className="space-y-2 rounded-xl border p-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={answered} onChange={e=>setAnswered(e.target.checked)}/>Marcar como oración respondida</label>{answered&&<RichTextEditor value={answeredNote} onChange={setAnsweredNote} placeholder="Cómo identificas o recuerdas la respuesta…"/>}</div>}
      {kind==="fasting"&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked/>Registrado</label>}
      <Button disabled={!content.trim()&&!prophecy.trim()} onClick={()=>void em.create.mutateAsync({user_id:user?.id,entry_date:date,kind,title:title||null,content:content||prophecy||null,prophecy:kind==="prophecy"?prophecy:null,scripture_reference:scripture||null,prayer_answered:kind==="prayer"?answered:null,answered_note:kind==="prayer"&&answered?answeredNote:null,fasting:kind==="fasting"}).then(clearEntry)}><Plus className="mr-1 h-4 w-4"/>Guardar registro</Button>
    </section>
    <section className="glass space-y-3 rounded-2xl p-4"><h2 className="font-semibold">Metas espirituales</h2><div className="grid gap-2 sm:grid-cols-4"><Input placeholder="Meta" value={goalTitle} onChange={e=>setGoalTitle(e.target.value)}/><Input type="date" value={goalDate} onChange={e=>setGoalDate(e.target.value)}/><Input type="number" min="0" max="100" placeholder="Progreso %" value={goalProgress} onChange={e=>setGoalProgress(e.target.value)}/><Button disabled={!goalTitle.trim()} onClick={()=>void gm.create.mutateAsync({user_id:user?.id,title:goalTitle.trim(),description:goalDescription||null,target_date:goalDate||null,progress:Number(goalProgress)||0}).then(()=>{setGoalTitle("");setGoalDescription("");setGoalDate("");setGoalProgress("0")})}><Plus className="mr-1 h-4 w-4"/>Agregar meta</Button></div><RichTextEditor value={goalDescription} onChange={setGoalDescription} placeholder="Qué significa esta meta para ti…"/>{(goals.data||[]).map((g:any)=><div key={g.id} className="rounded-xl border p-3"><div className="flex items-center gap-2"><span className="flex-1 font-medium">{g.title}</span><span className="text-xs">{Number(g.progress)||0}%</span><Button size="icon" variant="ghost" onClick={()=>void gm.remove.mutateAsync(g.id)}><Trash2 className="h-4 w-4 text-destructive"/></Button></div>{g.target_date&&<p className="text-xs text-muted-foreground">Meta: {g.target_date}</p>}<div className="mt-2 h-2 rounded-full bg-muted"><div className="h-2 rounded-full bg-primary" style={{width:Math.min(100,Math.max(0,Number(g.progress)||0))+"%"}}/></div></div>)}</section>
    <section className="space-y-2"><h2 className="font-semibold">Historial</h2>{(entries.data||[]).map((x:any)=><article key={x.id} className="glass rounded-2xl p-4"><p className="text-xs text-muted-foreground">{x.entry_date} · {x.kind}</p><h2 className="font-medium">{x.title||x.kind}</h2>{x.scripture_reference&&<p className="text-xs text-muted-foreground">{x.scripture_reference}</p>}<div className="prose prose-sm dark:prose-invert" dangerouslySetInnerHTML={{__html:x.content||x.prophecy||""}}/>{x.kind==="prophecy"&&x.prophecy&&<div className="mt-2 rounded-xl border p-3"><p className="text-xs font-medium">Profecía registrada</p><div className="prose prose-sm dark:prose-invert" dangerouslySetInnerHTML={{__html:x.prophecy}}/></div>}{x.prayer_answered&&<p className="mt-2 text-xs text-muted-foreground">✓ Oración marcada como respondida</p>}</article>)}</section>
  </PageShell>
}

function PageShell({icon,title,subtitle,children}:{icon:ReactNode;title:string;subtitle:string;children:ReactNode}){return <div className="space-y-5 pb-24"><div className="flex items-center gap-2">{icon}<h1 className="text-xl font-semibold">{title}</h1></div><p className="text-sm text-muted-foreground">{subtitle}</p>{children}</div>}
