/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NuevaClaveRouteImport } from './routes/nueva-clave'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedFinanzasRouteImport } from './routes/_authenticated/finanzas'
import { Route as AuthenticatedHabitosRouteImport } from './routes/_authenticated/habitos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPlaneadorRouteImport } from './routes/_authenticated/planeador'
import { Route as AuthenticatedSaludRouteImport } from './routes/_authenticated/salud'
import { Route as AuthenticatedAlarmasRouteImport } from './routes/_authenticated/alarmas'
import { Route as AuthenticatedModulosRouteImport } from './routes/_authenticated/modulos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaClaveRoute = NuevaClaveRouteImport.update({
  id: '/nueva-clave',
  path: '/nueva-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanzasRoute = AuthenticatedFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitosRoute = AuthenticatedHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaneadorRoute = AuthenticatedPlaneadorRouteImport.update({
  id: '/planeador',
  path: '/planeador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlarmasRoute = AuthenticatedAlarmasRouteImport.update({
  id: '/alarmas',
  path: '/alarmas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulosRoute = AuthenticatedModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSaludRoute = AuthenticatedSaludRouteImport.update({
  id: '/salud',
  path: '/salud',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planeador': typeof AuthenticatedPlaneadorRoute
  '/salud': typeof AuthenticatedSaludRoute
  '/alarmas': typeof AuthenticatedAlarmasRoute
  '/modulos': typeof AuthenticatedModulosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/finanzas': typeof AuthenticatedFinanzasRoute
  '/habitos': typeof AuthenticatedHabitosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planeador': typeof AuthenticatedPlaneadorRoute
  '/salud': typeof AuthenticatedSaludRoute
  '/alarmas': typeof AuthenticatedAlarmasRoute
  '/modulos': typeof AuthenticatedModulosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nueva-clave': typeof NuevaClaveRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/finanzas': typeof AuthenticatedFinanzasRoute
  '/_authenticated/habitos': typeof AuthenticatedHabitosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planeador': typeof AuthenticatedPlaneadorRoute
  '/_authenticated/salud': typeof AuthenticatedSaludRoute
  '/_authenticated/alarmas': typeof AuthenticatedAlarmasRoute
  '/_authenticated/modulos': typeof AuthenticatedModulosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nueva-clave'
    | '/diario'
    | '/finanzas'
    | '/habitos'
    | '/inicio'
    | '/perfil'
    | '/planeador'
    | '/salud'
    | '/alarmas'
    | '/modulos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nueva-clave'
    | '/diario'
    | '/finanzas'
    | '/habitos'
    | '/inicio'
    | '/perfil'
    | '/planeador'
    | '/salud'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nueva-clave'
    | '/_authenticated/diario'
    | '/_authenticated/finanzas'
    | '/_authenticated/habitos'
    | '/_authenticated/inicio'
    | '/_authenticated/perfil'
    | '/_authenticated/planeador'
    | '/_authenticated/salud'
    | '/_authenticated/alarmas'
    | '/_authenticated/modulos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NuevaClaveRoute: typeof NuevaClaveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-clave': {
      id: '/nueva-clave'
      path: '/nueva-clave'
      fullPath: '/nueva-clave'
      preLoaderRoute: typeof NuevaClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finanzas': {
      id: '/_authenticated/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof AuthenticatedFinanzasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habitos': {
      id: '/_authenticated/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AuthenticatedHabitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planeador': {
      id: '/_authenticated/planeador'
      path: '/planeador'
      fullPath: '/planeador'
      preLoaderRoute: typeof AuthenticatedPlaneadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alarmas': {
      id: '/_authenticated/alarmas'
      path: '/alarmas'
      fullPath: '/alarmas'
      preLoaderRoute: typeof AuthenticatedAlarmasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulos': {
      id: '/_authenticated/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof AuthenticatedModulosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salud': {
      id: '/_authenticated/salud'
      path: '/salud'
      fullPath: '/salud'
      preLoaderRoute: typeof AuthenticatedSaludRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedFinanzasRoute: typeof AuthenticatedFinanzasRoute
  AuthenticatedHabitosRoute: typeof AuthenticatedHabitosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlaneadorRoute: typeof AuthenticatedPlaneadorRoute
  AuthenticatedSaludRoute: typeof AuthenticatedSaludRoute
  AuthenticatedAlarmasRoute: typeof AuthenticatedAlarmasRoute
  AuthenticatedModulosRoute: typeof AuthenticatedModulosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedFinanzasRoute: AuthenticatedFinanzasRoute,
  AuthenticatedHabitosRoute: AuthenticatedHabitosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlaneadorRoute: AuthenticatedPlaneadorRoute,
  AuthenticatedSaludRoute: AuthenticatedSaludRoute,
  AuthenticatedAlarmasRoute: AuthenticatedAlarmasRoute,
  AuthenticatedModulosRoute: AuthenticatedModulosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NuevaClaveRoute: NuevaClaveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}